package main

import (
	"bytes"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/inflexa-ai/lint/golint/config"
)

func repo(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	write(t, filepath.Join(dir, "go.mod"), "module example.com/svc\n\ngo 1.26.0\n")
	write(t, filepath.Join(dir, "kernel", "ids", "ids.go"), "package ids\n\ntype UserID [16]byte\n")
	write(t, filepath.Join(dir, config.OverlayFile), "linters:\n  enable: [typedids]\n  settings:\n    custom:\n      typedids:\n        settings:\n          ids-package: example.com/svc/kernel/ids\n")
	return dir
}

func write(t *testing.T, path, text string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(text), 0o644); err != nil {
		t.Fatal(err)
	}
}

func read(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

func invoke(args ...string) (int, string, string) {
	var stdout, stderr bytes.Buffer
	code := run(args, &stdout, &stderr)
	return code, stdout.String(), stderr.String()
}

func TestFirstRun(t *testing.T) {
	dir := repo(t)
	code, _, stderr := invoke("-dir", dir)
	if code != 0 {
		t.Fatalf("exit %d: %s", code, stderr)
	}
	cfg := read(t, filepath.Join(dir, config.ConfigFile))
	if !strings.HasPrefix(cfg, "# Code generated by inflexa-lint-config") || !strings.Contains(cfg, "example.com/svc/kernel/ids") {
		t.Errorf("%s lacks the generator comment or the module path", config.ConfigFile)
	}
	if !regexp.MustCompile(`names:\n\s+- UserID\n`).MatchString(cfg) {
		t.Errorf("%s lacks the typed ID names:\n%s", config.ConfigFile, cfg)
	}
	rules := read(t, filepath.Join(dir, config.RulesFile))
	if !strings.HasPrefix(rules, "// Code generated by inflexa-lint-config") || !strings.Contains(rules, "func floatSum") {
		t.Errorf("%s lacks the generator comment or the ruleguard rules", config.RulesFile)
	}
	if !strings.Contains(stderr, "github.com/quasilyte/go-ruleguard/dsl") {
		t.Errorf("stderr %q does not name the dsl prerequisite of a go.mod without it", stderr)
	}
}

func TestOverlay(t *testing.T) {
	dir := repo(t)
	write(t, filepath.Join(dir, config.OverlayFile), "issues:\n  new-from-merge-base: main\n")
	if code, _, stderr := invoke("-dir", dir); code != 0 {
		t.Fatalf("exit %d: %s", code, stderr)
	}
	if cfg := read(t, filepath.Join(dir, config.ConfigFile)); !strings.Contains(cfg, "new-from-merge-base: main") {
		t.Error("the overlay did not reach the configuration")
	}
}

func TestCheckUnchanged(t *testing.T) {
	dir := repo(t)
	write(t, filepath.Join(dir, "go.mod"), "module example.com/svc\n\ngo 1.26.0\n\nrequire github.com/quasilyte/go-ruleguard/dsl v0.3.23\n")
	if code, _, stderr := invoke("-dir", dir); code != 0 || stderr != "" {
		t.Fatalf("exit %d: %q", code, stderr)
	}
	code, stdout, _ := invoke("-dir", dir, "-check")
	if code != 0 || stdout != "" {
		t.Errorf("exit %d, stdout %q; want 0 and no output", code, stdout)
	}
}

func TestCheckDrift(t *testing.T) {
	dir := repo(t)
	if code, _, stderr := invoke("-dir", dir); code != 0 {
		t.Fatalf("exit %d: %s", code, stderr)
	}
	path := filepath.Join(dir, config.ConfigFile)
	edited := read(t, path) + "# a local edit\n"
	write(t, path, edited)
	code, stdout, _ := invoke("-dir", dir, "-check")
	if code != 1 || stdout != config.ConfigFile+"\n" {
		t.Errorf("exit %d, stdout %q; want 1 and %s", code, stdout, config.ConfigFile)
	}
	if read(t, path) != edited {
		t.Error("-check changed a file")
	}
}

func TestCheckAbsent(t *testing.T) {
	dir := repo(t)
	code, stdout, _ := invoke("-dir", dir, "-check")
	if code != 1 || stdout != config.ConfigFile+"\n"+config.RulesFile+"\n" {
		t.Errorf("exit %d, stdout %q; want 1 and both files", code, stdout)
	}
	if _, err := os.Stat(filepath.Join(dir, config.ConfigFile)); !os.IsNotExist(err) {
		t.Error("-check wrote a file")
	}
}

func TestNoGoMod(t *testing.T) {
	code, _, stderr := invoke("-dir", t.TempDir())
	if code != 2 || !strings.Contains(stderr, "go.mod") {
		t.Errorf("exit %d, stderr %q; want 2 and a message that names go.mod", code, stderr)
	}
}

func TestCheckTypedIDChange(t *testing.T) {
	dir := repo(t)
	if code, _, stderr := invoke("-dir", dir); code != 0 {
		t.Fatalf("exit %d: %s", code, stderr)
	}
	write(t, filepath.Join(dir, "kernel", "ids", "ids.go"), "package ids\n\ntype (\n\tUserID [16]byte\n\tOrgID  [16]byte\n)\n")
	code, stdout, _ := invoke("-dir", dir, "-check")
	if code != 1 || stdout != config.ConfigFile+"\n" {
		t.Errorf("exit %d, stdout %q; want 1 and %s after a new typed ID", code, stdout, config.ConfigFile)
	}
}

func TestTypedIDPackageThatDoesNotLoad(t *testing.T) {
	dir := repo(t)
	if err := os.RemoveAll(filepath.Join(dir, "kernel")); err != nil {
		t.Fatal(err)
	}
	code, _, stderr := invoke("-dir", dir)
	if code != 2 || !strings.Contains(stderr, "example.com/svc/kernel/ids") {
		t.Errorf("exit %d, stderr %q; want 2 and a message that names the typed ID package", code, stderr)
	}
}
