// Package config renders the golangci-lint configuration of golint for a
// repository: the base configuration with the module path of the repository,
// the local overlay of the repository merged in, and the ruleguard rules file.
package config

import (
	"bytes"
	_ "embed"
	"fmt"
	"go/types"
	"strings"

	"go.yaml.in/yaml/v3"
	"golang.org/x/tools/go/packages"
)

const (
	ConfigFile  = ".golangci.yml"
	RulesFile   = "golangci/rules.go"
	OverlayFile = "golangci/overlay.yml"
)

//go:embed golangci.base.yml
var base string

//go:embed rules.go.txt
var rules string

const (
	configHeader = "# Code generated by inflexa-lint-config. DO NOT EDIT.\n" +
		"# Put the local choices of this repository in " + OverlayFile + ", then run inflexa-lint-config again.\n\n"
	rulesHeader = "// Code generated by inflexa-lint-config. DO NOT EDIT.\n\n"
)

// Render returns the content of ConfigFile and RulesFile for the module in
// dir. A non-empty overlay merges into the base: a mapping merges by key, a
// sequence of the overlay appends after the sequence of the base, and any
// other node of the overlay replaces the node of the base. Render then loads
// the typedids setting ids-package from dir and writes its typed ID names into
// the setting names. A name in the configuration salts the lint cache, thus a
// new typed ID invalidates the cached issues of each package.
func Render(dir, module string, overlay []byte) (map[string][]byte, error) {
	var doc yaml.Node
	if err := yaml.Unmarshal([]byte(strings.ReplaceAll(base, "{{module}}", module)), &doc); err != nil {
		return nil, fmt.Errorf("parse the base configuration: %w", err)
	}
	var over yaml.Node
	if err := yaml.Unmarshal(overlay, &over); err != nil {
		return nil, fmt.Errorf("parse %s: %w", OverlayFile, err)
	}
	if len(over.Content) > 0 {
		doc.Content[0] = merge(doc.Content[0], over.Content[0])
	}
	if err := fillTypedIDNames(dir, doc.Content[0]); err != nil {
		return nil, err
	}
	var out bytes.Buffer
	out.WriteString(configHeader)
	enc := yaml.NewEncoder(&out)
	enc.SetIndent(2)
	if err := enc.Encode(&doc); err != nil {
		return nil, fmt.Errorf("encode the configuration: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("encode the configuration: %w", err)
	}
	return map[string][]byte{
		ConfigFile: out.Bytes(),
		RulesFile:  []byte(rulesHeader + strings.ReplaceAll(rules, "{{module}}", module)),
	}, nil
}

func merge(base, over *yaml.Node) *yaml.Node {
	switch {
	case base.Kind == yaml.MappingNode && over.Kind == yaml.MappingNode:
		for i := 0; i+1 < len(over.Content); i += 2 {
			key, value := over.Content[i], over.Content[i+1]
			if j := keyIndex(base, key.Value); j >= 0 {
				base.Content[j+1] = merge(base.Content[j+1], value)
			} else {
				base.Content = append(base.Content, key, value)
			}
		}
		return base
	case base.Kind == yaml.SequenceNode && over.Kind == yaml.SequenceNode:
		base.Content = append(base.Content, over.Content...)
		return base
	default:
		return over
	}
}

func keyIndex(mapping *yaml.Node, key string) int {
	for i := 0; i+1 < len(mapping.Content); i += 2 {
		if mapping.Content[i].Value == key {
			return i
		}
	}
	return -1
}

func fillTypedIDNames(dir string, root *yaml.Node) error {
	settings := lookup(root, "linters", "settings", "custom", "typedids", "settings")
	pkg := lookup(settings, "ids-package")
	if pkg == nil || pkg.Value == "" {
		return nil
	}
	names, err := typedIDNames(dir, pkg.Value)
	if err != nil {
		return err
	}
	list := &yaml.Node{Kind: yaml.SequenceNode, Tag: "!!seq"}
	for _, n := range names {
		list.Content = append(list.Content, &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: n})
	}
	if i := keyIndex(settings, "names"); i >= 0 {
		settings.Content[i+1] = list
		return nil
	}
	settings.Content = append(settings.Content, &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: "names"}, list)
	return nil
}

// typedIDNames loads the package from dir and returns its type names with the
// underlying type [16]byte.
func typedIDNames(dir, path string) ([]string, error) {
	cfg := &packages.Config{Mode: packages.NeedName | packages.NeedTypes, Dir: dir}
	pkgs, err := packages.Load(cfg, path)
	if err != nil {
		return nil, fmt.Errorf("load the typed ID package %s: %w", path, err)
	}
	if len(pkgs) != 1 {
		return nil, fmt.Errorf("load the typed ID package %s: %d packages", path, len(pkgs))
	}
	if len(pkgs[0].Errors) > 0 {
		return nil, fmt.Errorf("load the typed ID package %s: %v", path, pkgs[0].Errors[0])
	}
	scope := pkgs[0].Types.Scope()
	var names []string
	for _, n := range scope.Names() {
		tn, ok := scope.Lookup(n).(*types.TypeName)
		if !ok {
			continue
		}
		arr, ok := tn.Type().Underlying().(*types.Array)
		if !ok || arr.Len() != 16 {
			continue
		}
		if b, ok := arr.Elem().Underlying().(*types.Basic); ok && b.Kind() == types.Byte {
			names = append(names, n)
		}
	}
	return names, nil
}

func lookup(node *yaml.Node, keys ...string) *yaml.Node {
	for _, key := range keys {
		if node == nil || node.Kind != yaml.MappingNode {
			return nil
		}
		i := keyIndex(node, key)
		if i < 0 {
			return nil
		}
		node = node.Content[i+1]
	}
	return node
}
